name: Daily Cron Job

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행
  workflow_dispatch:  # 수동으로 워크플로우를 실행할 수 있게 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Debug
      run: |
        pwd
        ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/requirements.txt
    - name: Run script
      env:
        ID: ${{ secrets.INSTAGRAM_ID }}
        PW: ${{ secrets.INSTAGRAM_PW }}
      run: |
        python crawl.py
    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USER}}
        password: ${{secrets.EMAIL_PASS}}
        subject: GitHub Actions job result
        body: The daily cron job has completed. Please check the results.
        to: jongseo1023@gachon.ac.kr
        from: GitHub Actions
