name: Daily Cron Job

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행
  workflow_dispatch:  # 수동으로 워크플로우를 실행할 수 있게 함

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 저장소에 쓰기 권한 부여
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      env:
        ID: ${{ secrets.INSTAGRAM_ID }}
        PW: ${{ secrets.INSTAGRAM_PW }}
      run: |
        python crawl.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add articles.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update articles.json" && git push)
    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USER}}
        password: ${{secrets.EMAIL_PASS}}
        subject: GitHub Actions job result
        body: The daily cron job has completed. Please check the results.
        to: jongseo1023@gachon.ac.kr
        from: GitHub Actions
